projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - server/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - server/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: server/graphql/API.ts
        docsFilePath: server/graphql
        region: ap-southeast-2
        apiId: np66kmimg5gwvf5rplh66ykgxi
        frontend: javascript
        framework: react
        maxDepth: 5
extensions:
  amplify:
    version: 3
