projects:
  Codegen Project:
    schemaPath: app/graphql/schema.json
    includes:
      - app/graphql/**/*.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: app/graphql/API.ts
        docsFilePath: app/graphql
        region: ap-southeast-2
        apiId: np66kmimg5gwvf5rplh66ykgxi
        frontend: javascript
        framework: react
        maxDepth: 5
extensions:
  amplify:
    version: 3
